development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: bp_news_development

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: bp_news_test<%= ENV["TEST_ENV_NUMBER"] %>
