development:
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  database: bp_news_dev
  socket: /tmp/mysql.sock
  username: USERNAME
  password:

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
